package com.selfhealing.model;

import com.selfhealing.enums.AiProviderType;
import com.selfhealing.enums.ValidationResult;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * Detailed record of a single healing attempt within a HealingJob.
 * Stores the AI diagnosis, generated patch, branch name, and CI validation outcome.
 */
@Document(collection = "healing_attempts")
@Getter
@Setter
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class HealingAttempt {

    @Id
    private String id;

    @Indexed
    private String healingJobId;

    private int attemptNumber;

    @Builder.Default
    private AiProviderType aiProvider = AiProviderType.GEMINI;

    /** Root cause diagnosis generated by AI */
    private String diagnosis;

    /** AI confidence score (0.0 to 1.0) */
    private Double confidence;

    /** Summary reasoning behind the proposed changes */
    private String reasoning;

    /** Serialized patch changes */
    private List<Map<String, Object>> changes;

    /** Branch where the patch was committed for validation */
    private String branchName;

    /** Validation workflow run ID on GitHub Actions */
    private Long validationRunId;

    /** CI validation outcome: PASS, FAIL, TIMEOUT */
    private ValidationResult validationResult;

    private String validationErrorLogs;

    @CreatedDate
    private Instant createdAt;
}
